apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-app
  namespace: local
  labels:
    app: version-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/andrii-codefresh/argocd-example-apps1.git
    targetRevision: HEAD
    # plugin:
    #   name: custom-plugin
    #   env:
    #     - name: ENV_VAR
    #       value: value
    #   parameters:
    #     - name: string-param
    #       string: example-string
    #     - name: array-param
    #       array:
    #         - item1
    #         - item2
    #     - name: map-param
    #       map:
    #         param-name: param-value
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
