apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-version-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/andrii-codefresh/local52-gs.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
